language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"

before_script:
  - npm install -g codeclimate-test-reporter

script: npm run test:cover

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
